### ISSUE TITLE
State of the Field

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#14]
The paper (https://github.com/holukas/dyco/blob/main/paper/paper.md) doesn't describe alternative methods or contrast DYCO's method with them. I think giving users a good sense of the trade-offs between various alternatives is important both for communicating the value of your work and for helping users make analysis choices appropriate to their situation.

openjournals/joss-reviews/issues/2575

**Comment by holukas** [comment]
I updated the paper and tried to re-word the _Statement of need_ section in a way so that it better reflects which unique features of DYCO can assist current flux processing schemes in calculating ecosystem fluxes (61ee45db749239be03bcadb8f2f7aa4d6e9fc123). To my knowledge, there is currently no openly available script or other software that offers similarly dynamic processing options for eddy covariance raw data.

**Comment by r-barnes** [comment]
Great, thanks!
