### ISSUE TITLE
Documentation comments

### ISSUE THREAD

**Issue by mccabete** [holukas/dyco#2]
**Statement of need**

- [x] Your [About](https://gitlab.ethz.ch/holukas/dyco-dynamic-lag-compensation/-/blob/master/README.md#L3) heading is pretty technical. Your Scientific Background header sets up the why DYCO is important really well. I'd switch the order of those two paragraphs, and rename the "About" heading, or provide a short summary of your scientific background in your about section. 

- [x] Who is your target audience? 

**Community Guidelines**
`DYCO` could use a quick statement outlining how to:

- [x] Report issues or problems `DYCO`

- [x] Seek support if `DYCO`doesn't work properly 

- [x] Because `DYCO` is/was tied to a ETH account, there should be a paragraph explaining how non ETH members can/should interact with `DYCO` when contributing, reporting issues or seeking help. Possibly this won’t be an issue if the wiki link is changed. Thanks again for migrating @holukas 

**Example Usage**
*Note, I'm currently not able to view the text of the wiki, so the below is from my notes. I can link to exact lines once the wiki link is updated*
- [ ] In the text for the Results from Phase 4 figure has the sentence

> "In this example, the covariance corresponds to the raw ecosystem flux of CO2, with negative values translating to CO2-uptake by the ecosystem (CO2 sink) and positive values translating to CO2-emission (CO2 source)."

This phrasing makes the axes on the Phase 4  diagrams difficult to interpret. Is this covariance in CO2 measurements? This sentence suggests that negative “covariance” values  should be interpreted literally as fluxes? Clearer units on the axes could clear this up. 

- [x] The Scientific Background talks about using `Dyco` for N2O fluxes, but the examples are only of CO2 fluxes. Could the example show how N2O monitoring is improved?

**Comment by holukas** [comment]
**Statement of need**
- I followed up on this suggestion by rearranging the paragraphs. The paper now starts with the science background, then mentions where DYCO comes in before listing the unique features the script has to offer.
- Regarding target audience, it is now mentioned more clearly that the files used are eddy covariance raw data files. In addition, I added additional info about the application of DYCO, i.e. where it is applied when eddy covariance fluxes are processed. 

**Community guidelines**
- I added a CONTRIBUTE file that lists the options for contributions.

**Example usage**
- I agree that the y-axis in the Phase 4 figure is difficult to interpret. Originally, I tried to keep this plot as simple as possible and kept "covariance" as y label because DYCO can be used on any time series data, not only EC data. In this case it is indeed the raw ecosystem flux before corrections which corresponds to the cross-covariance between the turbulent wind in m s-1 and the turbulent CO2 concentrations in umol mol-1) and is one of the first steps in the flux calculation. The negative values in this plot are CO2 uptake rates of the forest, the positive values are CO2 emission rates from the forest to the atmosphere. After going through all the texts and the code, I decided to replace the plot with two new plots showing fully processed N2O fluxes (see next point).
- Examples now show two plots for improved N2O calculations, with full units in the labels: [Example](https://github.com/holukas/dyco/wiki/Example). N2O plots were added in 3a1b38584f3618726a6f21ccbca3b6a05565de5f.

**Comment by mccabete** [comment]
Are we looking at the same versions? Right now on your main branch your paragraph listing the DYCO-specific features is before your scientific background.

**Comment by holukas** [comment]
For the moment, I have README arranged differently from the paper. I thought it would be a good idea to start with the features in the README since the script is mainly used by the flux community who are familiar with the background. For the paper, I thought it would be better to start with the background as introduction to the topic, then continue with the features. However, if you think it makes more sense to keep them structurally similar then I can adjust it accordingly.

**Comment by mccabete** [comment]
As long as you think the paper is what people who aren't familiar with DYCO will find first, it seems good to me!
